### ISSUE TITLE
Unable to change entries in theme editor

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#475]
When deleting a name or a colour in the theme editor the entry re-populates with the original entry.

[Video of issue](https://share.icloud.com/photos/0D_Q6MURc6kcwiKB-lFKDDUlA)

**Comment by timmo001** [comment]
I've seen this in all of the configuration section.

A workaround for now is to paste the text in, however this would not be very easy to do on mobile.

**Comment by thundergreen** [comment]
I face same issue on windoes and chrome browser

**Comment by aptonline** [comment]
Resolved in 2.0.2 confirmed.

**Comment by thundergreen** [comment]
Sorry but this issue is not fixed. Still facing same issue :/
