### ISSUE TITLE
Toggle entities on click of group title

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#54]
The ability to toggle groups on and off for lights etc.

Although I can add a group as an entity tapping this does nothing.

**Comment by timmo001** [comment]
Done! this will be added to the next release

**Comment by aptonline** [comment]
I still can’t get this to work. Added 'group.bedroom_lights' shows the entitity but doe nothing on tap. Running 'edge'.

**Comment by timmo001** [comment]
Please post your group's config. The group must have at least one HASS light or switch to work

**Comment by aptonline** [comment]
I have `group.bedroom_lights` in HA (created by HA) and works in HA front end.

and this is the config for Home Panel.

```
{
      "name": "Bedroom",
      "cards": [
        {
          "entity_id": "group.bedroom_lights",
          "icon": "lightbulb",
          "name": "All Lights"
        }
        ,
        {
          "entity_id": "switch.bedroom_lamp",
          "icon": "lamp"
        }
        ,
        {
          "entity_id": "light.bedroom_light",
          "icon": "ceiling-light"
        }
      ]
    }
```

**Comment by timmo001** [comment]
Groups won't work.

Switches and light will though. Make sure you have pulled the latest edge image, or wait for the next release

**Comment by aptonline** [comment]
Sorry did I miss something, I thought you added group toggle support? I updated to edge a few days ago.

**Comment by timmo001** [comment]
No I added support to toggle groups of cards, not support for hass groups.

![image](https://user-images.githubusercontent.com/28114703/44948678-e4275b00-ae19-11e8-8ac0-c9d718b6819d.png)

**Comment by aptonline** [comment]
In that case I think you miss understood my initial feature request. I want to be able to toggle HA groups on and off.
